### ISSUE TITLE
Crash on Minecraft 1.21.8 – NoSuchMethodError in DataFixer

### ISSUE THREAD

**Issue by Jamie314X** [JackFred2/ChestTracker#310]
**Minecraft Version:** 1.21.8  
**Chest Tracker Version:** 2.6.7+1.21.4  
**Fabric Loader Version:** 0.17.2  
**Other Mods:** Multiple, but confirmed reproducible with Chest Tracker alone.

**Description:**
When joining any server or loading a world, the game immediately crashes.  
This only happens on Minecraft 1.21.8 – Chest Tracker works fine on 1.21.4.

**Crash Log (relevant part):**
java.lang.NoSuchMethodError: 'net.minecraft.class_6595 net.minecraft.class_6489.method_37912()'
    at red.jackf.chesttracker.impl.datafix.Types.wrapInFixer(Types.java:24)
    at red.jackf.chesttracker.impl.memory.MemoryKeyImpl$Codecs.<clinit>(MemoryKeyImpl.java:205)
    ...
(FULL crash report attached below)

**Steps to reproduce:**
1. Install Chest Tracker 2.6.7+1.21.4 on Fabric 0.17.2 with Minecraft 1.21.8.
2. Join any multiplayer server or load a singleplayer world.
3. Immediate crash occurs.

**Expected behavior:**
Game loads normally and Chest Tracker works.

**Actual behavior:**
Immediate crash on world join due to NoSuchMethodError.

**Additional context:**
It seems method `method_37912` in `net.minecraft.class_6489` has been renamed or removed in MC 1.21.8, causing incompatibility with the DataFixer logic in Chest Tracker.

[crash-2025-08-12_14.11.07-client.txt](https://github.com/user-attachments/files/21735819/crash-2025-08-12_14.11.07-client.txt)

**Comment by mihoillo** [comment]
Mod isn't support 1.21.8 now, use alternative mods or run this on last supported version (1.21.4)

**Comment by xmorose** [comment]
@mihoillo what alternative mods are there?

**Comment by AlwaysHAK** [comment]
There's my updated version of ChestTracker & WhereIsIt. See [[update] 1.21.6/7/8](https://github.com/JackFred2/ChestTracker/pull/304) for more information.
