### ISSUE TITLE
Crash when opening shulker

### ISSUE THREAD

**Issue by NeNazvali** [JackFred2/ChestTracker#48]
**To Reproduce**
I downloaded 4 mods:
ChestTracker-1.18-1.1.3.

cloth-api-3.0.55

cloth-config-6.0.45-fabric

whereisit-1.18.1-1.14.7

After entering the game, and after entering the server, everything worked until I opened the brown shulker. After that, it seemed to save the world on the screen and the launcher crashed with the error

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void red.jackf.whereisit.client.RenderUtils.drawTextWithBackground(net.fabricmc.fabric.api.client.rendering.v1.WorldRenderContext, net.minecraft.class_243, net.minecraft.class_2561, int)'
End code: -1.

**Crash Report**
Below is the file.
[crash-2022-02-02_20.08.21-client.txt](https://github.com/JackFred2/ChestTracker/files/7988754/crash-2022-02-02_20.08.21-client.txt)

**Additional context**
I apologize if the translation is not clear to you, translated through Google Translate.

**Comment by JackFred2** [comment]
You're using an older version of ChestTracker; update to 1.1.9: https://www.curseforge.com/minecraft/mc-mods/chest-tracker/files/3602662

**Comment by NeNazvali** [comment]
Thank you. I thought where marked from 1.18.1 will not work on 1.18
